version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
install:
- cmd: appveyor downloadfile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
before_build:
- ps: nuget restore
build:
  verbosity: minimal
artifacts:
- path: nugets\**\*.nupkg

# Automatically register private account and/or project AppVeyor NuGet feeds.
nuget:
  account_feed: false
  project_feed: false
  disable_publish_on_pr: true     # disable publishing of .nupkg artifacts to account/project feeds for pull request builds

environment:
  access_token:
    secure: qNMRA5boyCslJ9JgiqjpLdHd0NvhQVWcjJx3ZMrcgrDz6DNFJnDsV7w9IZuhqwYZ

deploy:
  - provider: NuGet
    skip_symbols: false
    api_key:
      secure: A8JdC8M46tJ0WR+LjRq2cHuMfjCOEZ2xU7c75iayd7AnNvgqq7XrCKV5uGyeTpZL
      
notifications:
  - provider: Slack
    on_build_success: true
    on_build_failure: true
    incoming_webhook:
      secure: +5y63VhkKwOZVK264xwgH8gp7vI2cJivXvseQeSoYYNyH3wjOtid8Qz+gyNOjCGpI/xqxxJNwqFrL75ZPHYOYEKs9WhBWznTsFpJUAs5hxn1kcczMv6WYuwUzXJNEdqX6m47PnS7xrzUZJIRWNQCHRJCtN5VX+hXfVV6BT+tKQdRDeRr/LANhRLr2pAbIOGP
