// This code was generated by a tool.
// MaxParams: 15
using System;
using static System.Linq.Expressions.Expression;
using static HSNXT.SimpleTamper.Expressions.ExpressionsBase;

namespace HSNXT.SimpleTamper.Expressions
{
    public static partial class Callers
    {
        public static Func<T, TArg0, TResult> Instance1<T, TArg0, TResult>(string name)
        {
            var instance = ParameterInstance<T>();
            var arg0 = Parameter(typeof(TArg0), "arg0");

            return Lambda<Func<T, TArg0, TResult>>(
                Call(instance, name, null, arg0), instance, arg0 // return instance.name(arg0)
            ).Compile(); // (instance, arg0) => ...
        }

        public static Func<TArg0, TResult> Static1<T, TArg0, TResult>(string name)
        {
            var arg0 = Parameter(typeof(TArg0), "arg0");
            
            return Lambda<Func<TArg0, TResult>>(
                Call(Method<T>(name, typeof(TArg0)), arg0), arg0 // return T.name(arg0)
            ).Compile(); // (arg0) => ...
        }

        public static Action<T, TArg0> InstanceVoid1<T, TArg0>(string name)
        {
            var instance = ParameterInstance<T>();
            var arg0 = Parameter(typeof(TArg0), "arg0");
            
            return Lambda<Action<T, TArg0>>(
                Call(instance, name, null, arg0), instance, arg0 // instance.name(arg0)
            ).Compile(); // (instance, arg0) => ...
        }

        public static Action<TArg0> StaticVoid1<T, TArg0>(string name)
        {
            var arg0 = Parameter(typeof(TArg0), "arg0");
            
            return Lambda<Action<TArg0>>(
                Call(Method<T>(name, typeof(TArg0)), arg0), arg0 // T.name(arg0)
            ).Compile(); // (arg0) => ...
        }
        public static Func<T, TArg0, TArg1, TResult> Instance2<T, TArg0, TArg1, TResult>(string name)
        {
            var instance = ParameterInstance<T>();
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");

            return Lambda<Func<T, TArg0, TArg1, TResult>>(
                Call(instance, name, null, arg0, arg1), instance, arg0, arg1 // return instance.name(arg0, arg1)
            ).Compile(); // (instance, arg0, arg1) => ...
        }

        public static Func<TArg0, TArg1, TResult> Static2<T, TArg0, TArg1, TResult>(string name)
        {
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            
            return Lambda<Func<TArg0, TArg1, TResult>>(
                Call(Method<T>(name, typeof(TArg0), typeof(TArg1)), arg0, arg1), arg0, arg1 // return T.name(arg0, arg1)
            ).Compile(); // (arg0, arg1) => ...
        }

        public static Action<T, TArg0, TArg1> InstanceVoid2<T, TArg0, TArg1>(string name)
        {
            var instance = ParameterInstance<T>();
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            
            return Lambda<Action<T, TArg0, TArg1>>(
                Call(instance, name, null, arg0, arg1), instance, arg0, arg1 // instance.name(arg0, arg1)
            ).Compile(); // (instance, arg0, arg1) => ...
        }

        public static Action<TArg0, TArg1> StaticVoid2<T, TArg0, TArg1>(string name)
        {
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            
            return Lambda<Action<TArg0, TArg1>>(
                Call(Method<T>(name, typeof(TArg0), typeof(TArg1)), arg0, arg1), arg0, arg1 // T.name(arg0, arg1)
            ).Compile(); // (arg0, arg1) => ...
        }
        public static Func<T, TArg0, TArg1, TArg2, TResult> Instance3<T, TArg0, TArg1, TArg2, TResult>(string name)
        {
            var instance = ParameterInstance<T>();
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");

            return Lambda<Func<T, TArg0, TArg1, TArg2, TResult>>(
                Call(instance, name, null, arg0, arg1, arg2), instance, arg0, arg1, arg2 // return instance.name(arg0, arg1, arg2)
            ).Compile(); // (instance, arg0, arg1, arg2) => ...
        }

        public static Func<TArg0, TArg1, TArg2, TResult> Static3<T, TArg0, TArg1, TArg2, TResult>(string name)
        {
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            
            return Lambda<Func<TArg0, TArg1, TArg2, TResult>>(
                Call(Method<T>(name, typeof(TArg0), typeof(TArg1), typeof(TArg2)), arg0, arg1, arg2), arg0, arg1, arg2 // return T.name(arg0, arg1, arg2)
            ).Compile(); // (arg0, arg1, arg2) => ...
        }

        public static Action<T, TArg0, TArg1, TArg2> InstanceVoid3<T, TArg0, TArg1, TArg2>(string name)
        {
            var instance = ParameterInstance<T>();
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            
            return Lambda<Action<T, TArg0, TArg1, TArg2>>(
                Call(instance, name, null, arg0, arg1, arg2), instance, arg0, arg1, arg2 // instance.name(arg0, arg1, arg2)
            ).Compile(); // (instance, arg0, arg1, arg2) => ...
        }

        public static Action<TArg0, TArg1, TArg2> StaticVoid3<T, TArg0, TArg1, TArg2>(string name)
        {
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            
            return Lambda<Action<TArg0, TArg1, TArg2>>(
                Call(Method<T>(name, typeof(TArg0), typeof(TArg1), typeof(TArg2)), arg0, arg1, arg2), arg0, arg1, arg2 // T.name(arg0, arg1, arg2)
            ).Compile(); // (arg0, arg1, arg2) => ...
        }
        public static Func<T, TArg0, TArg1, TArg2, TArg3, TResult> Instance4<T, TArg0, TArg1, TArg2, TArg3, TResult>(string name)
        {
            var instance = ParameterInstance<T>();
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");

            return Lambda<Func<T, TArg0, TArg1, TArg2, TArg3, TResult>>(
                Call(instance, name, null, arg0, arg1, arg2, arg3), instance, arg0, arg1, arg2, arg3 // return instance.name(arg0, arg1, arg2, arg3)
            ).Compile(); // (instance, arg0, arg1, arg2, arg3) => ...
        }

        public static Func<TArg0, TArg1, TArg2, TArg3, TResult> Static4<T, TArg0, TArg1, TArg2, TArg3, TResult>(string name)
        {
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            
            return Lambda<Func<TArg0, TArg1, TArg2, TArg3, TResult>>(
                Call(Method<T>(name, typeof(TArg0), typeof(TArg1), typeof(TArg2), typeof(TArg3)), arg0, arg1, arg2, arg3), arg0, arg1, arg2, arg3 // return T.name(arg0, arg1, arg2, arg3)
            ).Compile(); // (arg0, arg1, arg2, arg3) => ...
        }

        public static Action<T, TArg0, TArg1, TArg2, TArg3> InstanceVoid4<T, TArg0, TArg1, TArg2, TArg3>(string name)
        {
            var instance = ParameterInstance<T>();
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            
            return Lambda<Action<T, TArg0, TArg1, TArg2, TArg3>>(
                Call(instance, name, null, arg0, arg1, arg2, arg3), instance, arg0, arg1, arg2, arg3 // instance.name(arg0, arg1, arg2, arg3)
            ).Compile(); // (instance, arg0, arg1, arg2, arg3) => ...
        }

        public static Action<TArg0, TArg1, TArg2, TArg3> StaticVoid4<T, TArg0, TArg1, TArg2, TArg3>(string name)
        {
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            
            return Lambda<Action<TArg0, TArg1, TArg2, TArg3>>(
                Call(Method<T>(name, typeof(TArg0), typeof(TArg1), typeof(TArg2), typeof(TArg3)), arg0, arg1, arg2, arg3), arg0, arg1, arg2, arg3 // T.name(arg0, arg1, arg2, arg3)
            ).Compile(); // (arg0, arg1, arg2, arg3) => ...
        }
        public static Func<T, TArg0, TArg1, TArg2, TArg3, TArg4, TResult> Instance5<T, TArg0, TArg1, TArg2, TArg3, TArg4, TResult>(string name)
        {
            var instance = ParameterInstance<T>();
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");

            return Lambda<Func<T, TArg0, TArg1, TArg2, TArg3, TArg4, TResult>>(
                Call(instance, name, null, arg0, arg1, arg2, arg3, arg4), instance, arg0, arg1, arg2, arg3, arg4 // return instance.name(arg0, arg1, arg2, arg3, arg4)
            ).Compile(); // (instance, arg0, arg1, arg2, arg3, arg4) => ...
        }

        public static Func<TArg0, TArg1, TArg2, TArg3, TArg4, TResult> Static5<T, TArg0, TArg1, TArg2, TArg3, TArg4, TResult>(string name)
        {
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            
            return Lambda<Func<TArg0, TArg1, TArg2, TArg3, TArg4, TResult>>(
                Call(Method<T>(name, typeof(TArg0), typeof(TArg1), typeof(TArg2), typeof(TArg3), typeof(TArg4)), arg0, arg1, arg2, arg3, arg4), arg0, arg1, arg2, arg3, arg4 // return T.name(arg0, arg1, arg2, arg3, arg4)
            ).Compile(); // (arg0, arg1, arg2, arg3, arg4) => ...
        }

        public static Action<T, TArg0, TArg1, TArg2, TArg3, TArg4> InstanceVoid5<T, TArg0, TArg1, TArg2, TArg3, TArg4>(string name)
        {
            var instance = ParameterInstance<T>();
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            
            return Lambda<Action<T, TArg0, TArg1, TArg2, TArg3, TArg4>>(
                Call(instance, name, null, arg0, arg1, arg2, arg3, arg4), instance, arg0, arg1, arg2, arg3, arg4 // instance.name(arg0, arg1, arg2, arg3, arg4)
            ).Compile(); // (instance, arg0, arg1, arg2, arg3, arg4) => ...
        }

        public static Action<TArg0, TArg1, TArg2, TArg3, TArg4> StaticVoid5<T, TArg0, TArg1, TArg2, TArg3, TArg4>(string name)
        {
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            
            return Lambda<Action<TArg0, TArg1, TArg2, TArg3, TArg4>>(
                Call(Method<T>(name, typeof(TArg0), typeof(TArg1), typeof(TArg2), typeof(TArg3), typeof(TArg4)), arg0, arg1, arg2, arg3, arg4), arg0, arg1, arg2, arg3, arg4 // T.name(arg0, arg1, arg2, arg3, arg4)
            ).Compile(); // (arg0, arg1, arg2, arg3, arg4) => ...
        }
        public static Func<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TResult> Instance6<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TResult>(string name)
        {
            var instance = ParameterInstance<T>();
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            var arg5 = Parameter(typeof(TArg5), "arg5");

            return Lambda<Func<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TResult>>(
                Call(instance, name, null, arg0, arg1, arg2, arg3, arg4, arg5), instance, arg0, arg1, arg2, arg3, arg4, arg5 // return instance.name(arg0, arg1, arg2, arg3, arg4, arg5)
            ).Compile(); // (instance, arg0, arg1, arg2, arg3, arg4, arg5) => ...
        }

        public static Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TResult> Static6<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TResult>(string name)
        {
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            var arg5 = Parameter(typeof(TArg5), "arg5");
            
            return Lambda<Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TResult>>(
                Call(Method<T>(name, typeof(TArg0), typeof(TArg1), typeof(TArg2), typeof(TArg3), typeof(TArg4), typeof(TArg5)), arg0, arg1, arg2, arg3, arg4, arg5), arg0, arg1, arg2, arg3, arg4, arg5 // return T.name(arg0, arg1, arg2, arg3, arg4, arg5)
            ).Compile(); // (arg0, arg1, arg2, arg3, arg4, arg5) => ...
        }

        public static Action<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5> InstanceVoid6<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5>(string name)
        {
            var instance = ParameterInstance<T>();
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            var arg5 = Parameter(typeof(TArg5), "arg5");
            
            return Lambda<Action<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5>>(
                Call(instance, name, null, arg0, arg1, arg2, arg3, arg4, arg5), instance, arg0, arg1, arg2, arg3, arg4, arg5 // instance.name(arg0, arg1, arg2, arg3, arg4, arg5)
            ).Compile(); // (instance, arg0, arg1, arg2, arg3, arg4, arg5) => ...
        }

        public static Action<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5> StaticVoid6<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5>(string name)
        {
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            var arg5 = Parameter(typeof(TArg5), "arg5");
            
            return Lambda<Action<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5>>(
                Call(Method<T>(name, typeof(TArg0), typeof(TArg1), typeof(TArg2), typeof(TArg3), typeof(TArg4), typeof(TArg5)), arg0, arg1, arg2, arg3, arg4, arg5), arg0, arg1, arg2, arg3, arg4, arg5 // T.name(arg0, arg1, arg2, arg3, arg4, arg5)
            ).Compile(); // (arg0, arg1, arg2, arg3, arg4, arg5) => ...
        }
        public static Func<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TResult> Instance7<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TResult>(string name)
        {
            var instance = ParameterInstance<T>();
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            var arg5 = Parameter(typeof(TArg5), "arg5");
            var arg6 = Parameter(typeof(TArg6), "arg6");

            return Lambda<Func<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TResult>>(
                Call(instance, name, null, arg0, arg1, arg2, arg3, arg4, arg5, arg6), instance, arg0, arg1, arg2, arg3, arg4, arg5, arg6 // return instance.name(arg0, arg1, arg2, arg3, arg4, arg5, arg6)
            ).Compile(); // (instance, arg0, arg1, arg2, arg3, arg4, arg5, arg6) => ...
        }

        public static Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TResult> Static7<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TResult>(string name)
        {
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            var arg5 = Parameter(typeof(TArg5), "arg5");
            var arg6 = Parameter(typeof(TArg6), "arg6");
            
            return Lambda<Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TResult>>(
                Call(Method<T>(name, typeof(TArg0), typeof(TArg1), typeof(TArg2), typeof(TArg3), typeof(TArg4), typeof(TArg5), typeof(TArg6)), arg0, arg1, arg2, arg3, arg4, arg5, arg6), arg0, arg1, arg2, arg3, arg4, arg5, arg6 // return T.name(arg0, arg1, arg2, arg3, arg4, arg5, arg6)
            ).Compile(); // (arg0, arg1, arg2, arg3, arg4, arg5, arg6) => ...
        }

        public static Action<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6> InstanceVoid7<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6>(string name)
        {
            var instance = ParameterInstance<T>();
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            var arg5 = Parameter(typeof(TArg5), "arg5");
            var arg6 = Parameter(typeof(TArg6), "arg6");
            
            return Lambda<Action<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6>>(
                Call(instance, name, null, arg0, arg1, arg2, arg3, arg4, arg5, arg6), instance, arg0, arg1, arg2, arg3, arg4, arg5, arg6 // instance.name(arg0, arg1, arg2, arg3, arg4, arg5, arg6)
            ).Compile(); // (instance, arg0, arg1, arg2, arg3, arg4, arg5, arg6) => ...
        }

        public static Action<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6> StaticVoid7<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6>(string name)
        {
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            var arg5 = Parameter(typeof(TArg5), "arg5");
            var arg6 = Parameter(typeof(TArg6), "arg6");
            
            return Lambda<Action<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6>>(
                Call(Method<T>(name, typeof(TArg0), typeof(TArg1), typeof(TArg2), typeof(TArg3), typeof(TArg4), typeof(TArg5), typeof(TArg6)), arg0, arg1, arg2, arg3, arg4, arg5, arg6), arg0, arg1, arg2, arg3, arg4, arg5, arg6 // T.name(arg0, arg1, arg2, arg3, arg4, arg5, arg6)
            ).Compile(); // (arg0, arg1, arg2, arg3, arg4, arg5, arg6) => ...
        }
        public static Func<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TResult> Instance8<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TResult>(string name)
        {
            var instance = ParameterInstance<T>();
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            var arg5 = Parameter(typeof(TArg5), "arg5");
            var arg6 = Parameter(typeof(TArg6), "arg6");
            var arg7 = Parameter(typeof(TArg7), "arg7");

            return Lambda<Func<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TResult>>(
                Call(instance, name, null, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7), instance, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7 // return instance.name(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7)
            ).Compile(); // (instance, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7) => ...
        }

        public static Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TResult> Static8<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TResult>(string name)
        {
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            var arg5 = Parameter(typeof(TArg5), "arg5");
            var arg6 = Parameter(typeof(TArg6), "arg6");
            var arg7 = Parameter(typeof(TArg7), "arg7");
            
            return Lambda<Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TResult>>(
                Call(Method<T>(name, typeof(TArg0), typeof(TArg1), typeof(TArg2), typeof(TArg3), typeof(TArg4), typeof(TArg5), typeof(TArg6), typeof(TArg7)), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7 // return T.name(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7)
            ).Compile(); // (arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7) => ...
        }

        public static Action<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7> InstanceVoid8<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7>(string name)
        {
            var instance = ParameterInstance<T>();
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            var arg5 = Parameter(typeof(TArg5), "arg5");
            var arg6 = Parameter(typeof(TArg6), "arg6");
            var arg7 = Parameter(typeof(TArg7), "arg7");
            
            return Lambda<Action<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7>>(
                Call(instance, name, null, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7), instance, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7 // instance.name(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7)
            ).Compile(); // (instance, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7) => ...
        }

        public static Action<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7> StaticVoid8<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7>(string name)
        {
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            var arg5 = Parameter(typeof(TArg5), "arg5");
            var arg6 = Parameter(typeof(TArg6), "arg6");
            var arg7 = Parameter(typeof(TArg7), "arg7");
            
            return Lambda<Action<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7>>(
                Call(Method<T>(name, typeof(TArg0), typeof(TArg1), typeof(TArg2), typeof(TArg3), typeof(TArg4), typeof(TArg5), typeof(TArg6), typeof(TArg7)), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7 // T.name(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7)
            ).Compile(); // (arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7) => ...
        }
        public static Func<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TResult> Instance9<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TResult>(string name)
        {
            var instance = ParameterInstance<T>();
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            var arg5 = Parameter(typeof(TArg5), "arg5");
            var arg6 = Parameter(typeof(TArg6), "arg6");
            var arg7 = Parameter(typeof(TArg7), "arg7");
            var arg8 = Parameter(typeof(TArg8), "arg8");

            return Lambda<Func<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TResult>>(
                Call(instance, name, null, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), instance, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8 // return instance.name(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8)
            ).Compile(); // (instance, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) => ...
        }

        public static Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TResult> Static9<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TResult>(string name)
        {
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            var arg5 = Parameter(typeof(TArg5), "arg5");
            var arg6 = Parameter(typeof(TArg6), "arg6");
            var arg7 = Parameter(typeof(TArg7), "arg7");
            var arg8 = Parameter(typeof(TArg8), "arg8");
            
            return Lambda<Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TResult>>(
                Call(Method<T>(name, typeof(TArg0), typeof(TArg1), typeof(TArg2), typeof(TArg3), typeof(TArg4), typeof(TArg5), typeof(TArg6), typeof(TArg7), typeof(TArg8)), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8 // return T.name(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8)
            ).Compile(); // (arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) => ...
        }

        public static Action<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8> InstanceVoid9<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8>(string name)
        {
            var instance = ParameterInstance<T>();
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            var arg5 = Parameter(typeof(TArg5), "arg5");
            var arg6 = Parameter(typeof(TArg6), "arg6");
            var arg7 = Parameter(typeof(TArg7), "arg7");
            var arg8 = Parameter(typeof(TArg8), "arg8");
            
            return Lambda<Action<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8>>(
                Call(instance, name, null, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), instance, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8 // instance.name(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8)
            ).Compile(); // (instance, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) => ...
        }

        public static Action<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8> StaticVoid9<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8>(string name)
        {
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            var arg5 = Parameter(typeof(TArg5), "arg5");
            var arg6 = Parameter(typeof(TArg6), "arg6");
            var arg7 = Parameter(typeof(TArg7), "arg7");
            var arg8 = Parameter(typeof(TArg8), "arg8");
            
            return Lambda<Action<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8>>(
                Call(Method<T>(name, typeof(TArg0), typeof(TArg1), typeof(TArg2), typeof(TArg3), typeof(TArg4), typeof(TArg5), typeof(TArg6), typeof(TArg7), typeof(TArg8)), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8 // T.name(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8)
            ).Compile(); // (arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) => ...
        }
        public static Func<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TResult> Instance10<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TResult>(string name)
        {
            var instance = ParameterInstance<T>();
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            var arg5 = Parameter(typeof(TArg5), "arg5");
            var arg6 = Parameter(typeof(TArg6), "arg6");
            var arg7 = Parameter(typeof(TArg7), "arg7");
            var arg8 = Parameter(typeof(TArg8), "arg8");
            var arg9 = Parameter(typeof(TArg9), "arg9");

            return Lambda<Func<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TResult>>(
                Call(instance, name, null, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), instance, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9 // return instance.name(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9)
            ).Compile(); // (instance, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) => ...
        }

        public static Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TResult> Static10<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TResult>(string name)
        {
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            var arg5 = Parameter(typeof(TArg5), "arg5");
            var arg6 = Parameter(typeof(TArg6), "arg6");
            var arg7 = Parameter(typeof(TArg7), "arg7");
            var arg8 = Parameter(typeof(TArg8), "arg8");
            var arg9 = Parameter(typeof(TArg9), "arg9");
            
            return Lambda<Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TResult>>(
                Call(Method<T>(name, typeof(TArg0), typeof(TArg1), typeof(TArg2), typeof(TArg3), typeof(TArg4), typeof(TArg5), typeof(TArg6), typeof(TArg7), typeof(TArg8), typeof(TArg9)), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9 // return T.name(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9)
            ).Compile(); // (arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) => ...
        }

        public static Action<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9> InstanceVoid10<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9>(string name)
        {
            var instance = ParameterInstance<T>();
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            var arg5 = Parameter(typeof(TArg5), "arg5");
            var arg6 = Parameter(typeof(TArg6), "arg6");
            var arg7 = Parameter(typeof(TArg7), "arg7");
            var arg8 = Parameter(typeof(TArg8), "arg8");
            var arg9 = Parameter(typeof(TArg9), "arg9");
            
            return Lambda<Action<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9>>(
                Call(instance, name, null, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), instance, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9 // instance.name(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9)
            ).Compile(); // (instance, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) => ...
        }

        public static Action<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9> StaticVoid10<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9>(string name)
        {
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            var arg5 = Parameter(typeof(TArg5), "arg5");
            var arg6 = Parameter(typeof(TArg6), "arg6");
            var arg7 = Parameter(typeof(TArg7), "arg7");
            var arg8 = Parameter(typeof(TArg8), "arg8");
            var arg9 = Parameter(typeof(TArg9), "arg9");
            
            return Lambda<Action<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9>>(
                Call(Method<T>(name, typeof(TArg0), typeof(TArg1), typeof(TArg2), typeof(TArg3), typeof(TArg4), typeof(TArg5), typeof(TArg6), typeof(TArg7), typeof(TArg8), typeof(TArg9)), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9 // T.name(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9)
            ).Compile(); // (arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) => ...
        }
        public static Func<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TResult> Instance11<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TResult>(string name)
        {
            var instance = ParameterInstance<T>();
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            var arg5 = Parameter(typeof(TArg5), "arg5");
            var arg6 = Parameter(typeof(TArg6), "arg6");
            var arg7 = Parameter(typeof(TArg7), "arg7");
            var arg8 = Parameter(typeof(TArg8), "arg8");
            var arg9 = Parameter(typeof(TArg9), "arg9");
            var arg10 = Parameter(typeof(TArg10), "arg10");

            return Lambda<Func<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TResult>>(
                Call(instance, name, null, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10), instance, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10 // return instance.name(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10)
            ).Compile(); // (instance, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) => ...
        }

        public static Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TResult> Static11<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TResult>(string name)
        {
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            var arg5 = Parameter(typeof(TArg5), "arg5");
            var arg6 = Parameter(typeof(TArg6), "arg6");
            var arg7 = Parameter(typeof(TArg7), "arg7");
            var arg8 = Parameter(typeof(TArg8), "arg8");
            var arg9 = Parameter(typeof(TArg9), "arg9");
            var arg10 = Parameter(typeof(TArg10), "arg10");
            
            return Lambda<Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TResult>>(
                Call(Method<T>(name, typeof(TArg0), typeof(TArg1), typeof(TArg2), typeof(TArg3), typeof(TArg4), typeof(TArg5), typeof(TArg6), typeof(TArg7), typeof(TArg8), typeof(TArg9), typeof(TArg10)), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10 // return T.name(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10)
            ).Compile(); // (arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) => ...
        }

        public static Action<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10> InstanceVoid11<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10>(string name)
        {
            var instance = ParameterInstance<T>();
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            var arg5 = Parameter(typeof(TArg5), "arg5");
            var arg6 = Parameter(typeof(TArg6), "arg6");
            var arg7 = Parameter(typeof(TArg7), "arg7");
            var arg8 = Parameter(typeof(TArg8), "arg8");
            var arg9 = Parameter(typeof(TArg9), "arg9");
            var arg10 = Parameter(typeof(TArg10), "arg10");
            
            return Lambda<Action<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10>>(
                Call(instance, name, null, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10), instance, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10 // instance.name(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10)
            ).Compile(); // (instance, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) => ...
        }

        public static Action<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10> StaticVoid11<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10>(string name)
        {
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            var arg5 = Parameter(typeof(TArg5), "arg5");
            var arg6 = Parameter(typeof(TArg6), "arg6");
            var arg7 = Parameter(typeof(TArg7), "arg7");
            var arg8 = Parameter(typeof(TArg8), "arg8");
            var arg9 = Parameter(typeof(TArg9), "arg9");
            var arg10 = Parameter(typeof(TArg10), "arg10");
            
            return Lambda<Action<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10>>(
                Call(Method<T>(name, typeof(TArg0), typeof(TArg1), typeof(TArg2), typeof(TArg3), typeof(TArg4), typeof(TArg5), typeof(TArg6), typeof(TArg7), typeof(TArg8), typeof(TArg9), typeof(TArg10)), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10 // T.name(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10)
            ).Compile(); // (arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) => ...
        }
        public static Func<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TResult> Instance12<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TResult>(string name)
        {
            var instance = ParameterInstance<T>();
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            var arg5 = Parameter(typeof(TArg5), "arg5");
            var arg6 = Parameter(typeof(TArg6), "arg6");
            var arg7 = Parameter(typeof(TArg7), "arg7");
            var arg8 = Parameter(typeof(TArg8), "arg8");
            var arg9 = Parameter(typeof(TArg9), "arg9");
            var arg10 = Parameter(typeof(TArg10), "arg10");
            var arg11 = Parameter(typeof(TArg11), "arg11");

            return Lambda<Func<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TResult>>(
                Call(instance, name, null, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11), instance, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11 // return instance.name(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11)
            ).Compile(); // (instance, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11) => ...
        }

        public static Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TResult> Static12<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TResult>(string name)
        {
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            var arg5 = Parameter(typeof(TArg5), "arg5");
            var arg6 = Parameter(typeof(TArg6), "arg6");
            var arg7 = Parameter(typeof(TArg7), "arg7");
            var arg8 = Parameter(typeof(TArg8), "arg8");
            var arg9 = Parameter(typeof(TArg9), "arg9");
            var arg10 = Parameter(typeof(TArg10), "arg10");
            var arg11 = Parameter(typeof(TArg11), "arg11");
            
            return Lambda<Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TResult>>(
                Call(Method<T>(name, typeof(TArg0), typeof(TArg1), typeof(TArg2), typeof(TArg3), typeof(TArg4), typeof(TArg5), typeof(TArg6), typeof(TArg7), typeof(TArg8), typeof(TArg9), typeof(TArg10), typeof(TArg11)), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11 // return T.name(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11)
            ).Compile(); // (arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11) => ...
        }

        public static Action<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11> InstanceVoid12<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11>(string name)
        {
            var instance = ParameterInstance<T>();
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            var arg5 = Parameter(typeof(TArg5), "arg5");
            var arg6 = Parameter(typeof(TArg6), "arg6");
            var arg7 = Parameter(typeof(TArg7), "arg7");
            var arg8 = Parameter(typeof(TArg8), "arg8");
            var arg9 = Parameter(typeof(TArg9), "arg9");
            var arg10 = Parameter(typeof(TArg10), "arg10");
            var arg11 = Parameter(typeof(TArg11), "arg11");
            
            return Lambda<Action<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11>>(
                Call(instance, name, null, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11), instance, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11 // instance.name(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11)
            ).Compile(); // (instance, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11) => ...
        }

        public static Action<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11> StaticVoid12<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11>(string name)
        {
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            var arg5 = Parameter(typeof(TArg5), "arg5");
            var arg6 = Parameter(typeof(TArg6), "arg6");
            var arg7 = Parameter(typeof(TArg7), "arg7");
            var arg8 = Parameter(typeof(TArg8), "arg8");
            var arg9 = Parameter(typeof(TArg9), "arg9");
            var arg10 = Parameter(typeof(TArg10), "arg10");
            var arg11 = Parameter(typeof(TArg11), "arg11");
            
            return Lambda<Action<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11>>(
                Call(Method<T>(name, typeof(TArg0), typeof(TArg1), typeof(TArg2), typeof(TArg3), typeof(TArg4), typeof(TArg5), typeof(TArg6), typeof(TArg7), typeof(TArg8), typeof(TArg9), typeof(TArg10), typeof(TArg11)), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11 // T.name(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11)
            ).Compile(); // (arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11) => ...
        }
        public static Func<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TResult> Instance13<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TResult>(string name)
        {
            var instance = ParameterInstance<T>();
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            var arg5 = Parameter(typeof(TArg5), "arg5");
            var arg6 = Parameter(typeof(TArg6), "arg6");
            var arg7 = Parameter(typeof(TArg7), "arg7");
            var arg8 = Parameter(typeof(TArg8), "arg8");
            var arg9 = Parameter(typeof(TArg9), "arg9");
            var arg10 = Parameter(typeof(TArg10), "arg10");
            var arg11 = Parameter(typeof(TArg11), "arg11");
            var arg12 = Parameter(typeof(TArg12), "arg12");

            return Lambda<Func<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TResult>>(
                Call(instance, name, null, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12), instance, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12 // return instance.name(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12)
            ).Compile(); // (instance, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12) => ...
        }

        public static Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TResult> Static13<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TResult>(string name)
        {
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            var arg5 = Parameter(typeof(TArg5), "arg5");
            var arg6 = Parameter(typeof(TArg6), "arg6");
            var arg7 = Parameter(typeof(TArg7), "arg7");
            var arg8 = Parameter(typeof(TArg8), "arg8");
            var arg9 = Parameter(typeof(TArg9), "arg9");
            var arg10 = Parameter(typeof(TArg10), "arg10");
            var arg11 = Parameter(typeof(TArg11), "arg11");
            var arg12 = Parameter(typeof(TArg12), "arg12");
            
            return Lambda<Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TResult>>(
                Call(Method<T>(name, typeof(TArg0), typeof(TArg1), typeof(TArg2), typeof(TArg3), typeof(TArg4), typeof(TArg5), typeof(TArg6), typeof(TArg7), typeof(TArg8), typeof(TArg9), typeof(TArg10), typeof(TArg11), typeof(TArg12)), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12 // return T.name(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12)
            ).Compile(); // (arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12) => ...
        }

        public static Action<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12> InstanceVoid13<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12>(string name)
        {
            var instance = ParameterInstance<T>();
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            var arg5 = Parameter(typeof(TArg5), "arg5");
            var arg6 = Parameter(typeof(TArg6), "arg6");
            var arg7 = Parameter(typeof(TArg7), "arg7");
            var arg8 = Parameter(typeof(TArg8), "arg8");
            var arg9 = Parameter(typeof(TArg9), "arg9");
            var arg10 = Parameter(typeof(TArg10), "arg10");
            var arg11 = Parameter(typeof(TArg11), "arg11");
            var arg12 = Parameter(typeof(TArg12), "arg12");
            
            return Lambda<Action<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12>>(
                Call(instance, name, null, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12), instance, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12 // instance.name(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12)
            ).Compile(); // (instance, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12) => ...
        }

        public static Action<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12> StaticVoid13<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12>(string name)
        {
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            var arg5 = Parameter(typeof(TArg5), "arg5");
            var arg6 = Parameter(typeof(TArg6), "arg6");
            var arg7 = Parameter(typeof(TArg7), "arg7");
            var arg8 = Parameter(typeof(TArg8), "arg8");
            var arg9 = Parameter(typeof(TArg9), "arg9");
            var arg10 = Parameter(typeof(TArg10), "arg10");
            var arg11 = Parameter(typeof(TArg11), "arg11");
            var arg12 = Parameter(typeof(TArg12), "arg12");
            
            return Lambda<Action<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12>>(
                Call(Method<T>(name, typeof(TArg0), typeof(TArg1), typeof(TArg2), typeof(TArg3), typeof(TArg4), typeof(TArg5), typeof(TArg6), typeof(TArg7), typeof(TArg8), typeof(TArg9), typeof(TArg10), typeof(TArg11), typeof(TArg12)), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12 // T.name(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12)
            ).Compile(); // (arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12) => ...
        }
        public static Func<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TResult> Instance14<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TResult>(string name)
        {
            var instance = ParameterInstance<T>();
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            var arg5 = Parameter(typeof(TArg5), "arg5");
            var arg6 = Parameter(typeof(TArg6), "arg6");
            var arg7 = Parameter(typeof(TArg7), "arg7");
            var arg8 = Parameter(typeof(TArg8), "arg8");
            var arg9 = Parameter(typeof(TArg9), "arg9");
            var arg10 = Parameter(typeof(TArg10), "arg10");
            var arg11 = Parameter(typeof(TArg11), "arg11");
            var arg12 = Parameter(typeof(TArg12), "arg12");
            var arg13 = Parameter(typeof(TArg13), "arg13");

            return Lambda<Func<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TResult>>(
                Call(instance, name, null, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13), instance, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13 // return instance.name(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13)
            ).Compile(); // (instance, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13) => ...
        }

        public static Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TResult> Static14<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TResult>(string name)
        {
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            var arg5 = Parameter(typeof(TArg5), "arg5");
            var arg6 = Parameter(typeof(TArg6), "arg6");
            var arg7 = Parameter(typeof(TArg7), "arg7");
            var arg8 = Parameter(typeof(TArg8), "arg8");
            var arg9 = Parameter(typeof(TArg9), "arg9");
            var arg10 = Parameter(typeof(TArg10), "arg10");
            var arg11 = Parameter(typeof(TArg11), "arg11");
            var arg12 = Parameter(typeof(TArg12), "arg12");
            var arg13 = Parameter(typeof(TArg13), "arg13");
            
            return Lambda<Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TResult>>(
                Call(Method<T>(name, typeof(TArg0), typeof(TArg1), typeof(TArg2), typeof(TArg3), typeof(TArg4), typeof(TArg5), typeof(TArg6), typeof(TArg7), typeof(TArg8), typeof(TArg9), typeof(TArg10), typeof(TArg11), typeof(TArg12), typeof(TArg13)), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13 // return T.name(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13)
            ).Compile(); // (arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13) => ...
        }

        public static Action<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13> InstanceVoid14<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13>(string name)
        {
            var instance = ParameterInstance<T>();
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            var arg5 = Parameter(typeof(TArg5), "arg5");
            var arg6 = Parameter(typeof(TArg6), "arg6");
            var arg7 = Parameter(typeof(TArg7), "arg7");
            var arg8 = Parameter(typeof(TArg8), "arg8");
            var arg9 = Parameter(typeof(TArg9), "arg9");
            var arg10 = Parameter(typeof(TArg10), "arg10");
            var arg11 = Parameter(typeof(TArg11), "arg11");
            var arg12 = Parameter(typeof(TArg12), "arg12");
            var arg13 = Parameter(typeof(TArg13), "arg13");
            
            return Lambda<Action<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13>>(
                Call(instance, name, null, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13), instance, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13 // instance.name(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13)
            ).Compile(); // (instance, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13) => ...
        }

        public static Action<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13> StaticVoid14<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13>(string name)
        {
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            var arg5 = Parameter(typeof(TArg5), "arg5");
            var arg6 = Parameter(typeof(TArg6), "arg6");
            var arg7 = Parameter(typeof(TArg7), "arg7");
            var arg8 = Parameter(typeof(TArg8), "arg8");
            var arg9 = Parameter(typeof(TArg9), "arg9");
            var arg10 = Parameter(typeof(TArg10), "arg10");
            var arg11 = Parameter(typeof(TArg11), "arg11");
            var arg12 = Parameter(typeof(TArg12), "arg12");
            var arg13 = Parameter(typeof(TArg13), "arg13");
            
            return Lambda<Action<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13>>(
                Call(Method<T>(name, typeof(TArg0), typeof(TArg1), typeof(TArg2), typeof(TArg3), typeof(TArg4), typeof(TArg5), typeof(TArg6), typeof(TArg7), typeof(TArg8), typeof(TArg9), typeof(TArg10), typeof(TArg11), typeof(TArg12), typeof(TArg13)), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13 // T.name(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13)
            ).Compile(); // (arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13) => ...
        }
        public static Func<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TResult> Instance15<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TResult>(string name)
        {
            var instance = ParameterInstance<T>();
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            var arg5 = Parameter(typeof(TArg5), "arg5");
            var arg6 = Parameter(typeof(TArg6), "arg6");
            var arg7 = Parameter(typeof(TArg7), "arg7");
            var arg8 = Parameter(typeof(TArg8), "arg8");
            var arg9 = Parameter(typeof(TArg9), "arg9");
            var arg10 = Parameter(typeof(TArg10), "arg10");
            var arg11 = Parameter(typeof(TArg11), "arg11");
            var arg12 = Parameter(typeof(TArg12), "arg12");
            var arg13 = Parameter(typeof(TArg13), "arg13");
            var arg14 = Parameter(typeof(TArg14), "arg14");

            return Lambda<Func<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TResult>>(
                Call(instance, name, null, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14), instance, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14 // return instance.name(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14)
            ).Compile(); // (instance, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14) => ...
        }

        public static Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TResult> Static15<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TResult>(string name)
        {
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            var arg5 = Parameter(typeof(TArg5), "arg5");
            var arg6 = Parameter(typeof(TArg6), "arg6");
            var arg7 = Parameter(typeof(TArg7), "arg7");
            var arg8 = Parameter(typeof(TArg8), "arg8");
            var arg9 = Parameter(typeof(TArg9), "arg9");
            var arg10 = Parameter(typeof(TArg10), "arg10");
            var arg11 = Parameter(typeof(TArg11), "arg11");
            var arg12 = Parameter(typeof(TArg12), "arg12");
            var arg13 = Parameter(typeof(TArg13), "arg13");
            var arg14 = Parameter(typeof(TArg14), "arg14");
            
            return Lambda<Func<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TResult>>(
                Call(Method<T>(name, typeof(TArg0), typeof(TArg1), typeof(TArg2), typeof(TArg3), typeof(TArg4), typeof(TArg5), typeof(TArg6), typeof(TArg7), typeof(TArg8), typeof(TArg9), typeof(TArg10), typeof(TArg11), typeof(TArg12), typeof(TArg13), typeof(TArg14)), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14 // return T.name(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14)
            ).Compile(); // (arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14) => ...
        }

        public static Action<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14> InstanceVoid15<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14>(string name)
        {
            var instance = ParameterInstance<T>();
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            var arg5 = Parameter(typeof(TArg5), "arg5");
            var arg6 = Parameter(typeof(TArg6), "arg6");
            var arg7 = Parameter(typeof(TArg7), "arg7");
            var arg8 = Parameter(typeof(TArg8), "arg8");
            var arg9 = Parameter(typeof(TArg9), "arg9");
            var arg10 = Parameter(typeof(TArg10), "arg10");
            var arg11 = Parameter(typeof(TArg11), "arg11");
            var arg12 = Parameter(typeof(TArg12), "arg12");
            var arg13 = Parameter(typeof(TArg13), "arg13");
            var arg14 = Parameter(typeof(TArg14), "arg14");
            
            return Lambda<Action<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14>>(
                Call(instance, name, null, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14), instance, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14 // instance.name(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14)
            ).Compile(); // (instance, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14) => ...
        }

        public static Action<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14> StaticVoid15<T, TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14>(string name)
        {
            var arg0 = Parameter(typeof(TArg0), "arg0");
            var arg1 = Parameter(typeof(TArg1), "arg1");
            var arg2 = Parameter(typeof(TArg2), "arg2");
            var arg3 = Parameter(typeof(TArg3), "arg3");
            var arg4 = Parameter(typeof(TArg4), "arg4");
            var arg5 = Parameter(typeof(TArg5), "arg5");
            var arg6 = Parameter(typeof(TArg6), "arg6");
            var arg7 = Parameter(typeof(TArg7), "arg7");
            var arg8 = Parameter(typeof(TArg8), "arg8");
            var arg9 = Parameter(typeof(TArg9), "arg9");
            var arg10 = Parameter(typeof(TArg10), "arg10");
            var arg11 = Parameter(typeof(TArg11), "arg11");
            var arg12 = Parameter(typeof(TArg12), "arg12");
            var arg13 = Parameter(typeof(TArg13), "arg13");
            var arg14 = Parameter(typeof(TArg14), "arg14");
            
            return Lambda<Action<TArg0, TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14>>(
                Call(Method<T>(name, typeof(TArg0), typeof(TArg1), typeof(TArg2), typeof(TArg3), typeof(TArg4), typeof(TArg5), typeof(TArg6), typeof(TArg7), typeof(TArg8), typeof(TArg9), typeof(TArg10), typeof(TArg11), typeof(TArg12), typeof(TArg13), typeof(TArg14)), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14 // T.name(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14)
            ).Compile(); // (arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14) => ...
        }
    }
}